version: '3.8'

services:
  facebook-scraper:

    build: .

    environment:
      - DATABASE_URL=postgresql://root:root@postgresql:5432/facebook
    depends_on:
      - postgresql
    ports:
      - 8000:8000
    restart: always
    container_name: facebook-scraper
  postgresql:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=facebook
    container_name: postgresql
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8006:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.root"
      PGADMIN_DEFAULT_PASSWORD: "root"
    container_name: pgadmin